services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    # If you need environment variables, uncomment and add them:
    # environment:
#   - NODE_ENV=production