name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/website:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/website:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/website:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/website:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/website:buildcache,mode=max
          build-args: |
            NEXT_PUBLIC_BUILD_TIME=${{ steps.date.outputs.date }}
          # Enable BuildKit features for better caching and smaller image size
          provenance: false
          sbom: false
          outputs: type=registry,name=${{ secrets.DOCKERHUB_USERNAME }}/website

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}