name: Cleanup Old Docker Images

on:
  schedule:
    # Run monthly on the 1st day of the month at 1AM
    - cron: '0 1 1 * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cleanup old images
        run: |
          # Get list of all tags
          TAGS=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/website/tags?page_size=1000" | \
            jq -r '.results[].name')
          
          # Keep latest, buildcache, and the 10 most recent date tags
          DATE_TAGS=$(echo "$TAGS" | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' | sort -r | tail -n +11)
          
          # Delete old date tags
          for TAG in $DATE_TAGS; do
            echo "Deleting tag: $TAG"
            curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/website/tags/$TAG/"
          done